name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag geant_tut:$(date +%s)
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        tags: geant_tut:latest
        outputs: type=docker,dest=/tmp/myimage.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: geant_tut
        path: /tmp/myimage.tar
        
